name: DevInfra

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  breaking-changes-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: angular/dev-infra/github-actions/breaking-changes-label@3d9cbf3a729b8a567e8a716f4bdfe30e7a201512
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
